// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2xsWMbGxJMd5f6YcntvxRn
// Component: 2ZrzIt7PWj
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 2xsWMbGxJMd5f6YcntvxRn/projectcss
import sty from "./PlasmicThanks.module.css"; // plasmic-import: 2ZrzIt7PWj/css

export type PlasmicThanks__VariantMembers = {};
export type PlasmicThanks__VariantsArgs = {};
type VariantPropType = keyof PlasmicThanks__VariantsArgs;
export const PlasmicThanks__VariantProps = new Array<VariantPropType>();

export type PlasmicThanks__ArgsType = {};
type ArgPropType = keyof PlasmicThanks__ArgsType;
export const PlasmicThanks__ArgProps = new Array<ArgPropType>();

export type PlasmicThanks__OverridesType = {
  root?: p.Flex<"div">;
  frame1?: p.Flex<"div">;
  thankYou?: p.Flex<"div">;
};

export interface DefaultThanksProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicThanks__RenderFunc(props: {
  variants: PlasmicThanks__VariantsArgs;
  args: PlasmicThanks__ArgsType;
  overrides: PlasmicThanks__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      {}

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"frame1"}
            data-plasmic-override={overrides.frame1}
            className={classNames(projectcss.all, sty.frame1)}
          >
            <div
              data-plasmic-name={"thankYou"}
              data-plasmic-override={overrides.thankYou}
              className={classNames(projectcss.all, sty.thankYou)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4Ap4H
                )}
              >
                {"Thank you"}
              </div>
            </div>

            <a
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__vndj
              )}
              href={`/`}
            >
              {"go back to page"}
            </a>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "frame1", "thankYou"],
  frame1: ["frame1", "thankYou"],
  thankYou: ["thankYou"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  frame1: "div";
  thankYou: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicThanks__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicThanks__VariantsArgs;
    args?: PlasmicThanks__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicThanks__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicThanks__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicThanks__ArgProps,
          internalVariantPropNames: PlasmicThanks__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicThanks__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicThanks";
  } else {
    func.displayName = `PlasmicThanks.${nodeName}`;
  }
  return func;
}

export const PlasmicThanks = Object.assign(
  // Top-level PlasmicThanks renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    frame1: makeNodeComponent("frame1"),
    thankYou: makeNodeComponent("thankYou"),

    // Metadata about props expected for PlasmicThanks
    internalVariantProps: PlasmicThanks__VariantProps,
    internalArgProps: PlasmicThanks__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicThanks;
/* prettier-ignore-end */
